### ISSUE TITLE
麻烦问一下怎样获得ipa的 build 版本号

### ISSUE THREAD

**Issue by jeffy7** [MellongLau/AMAppExportToIPA-Xcode-Plugin#10]

**Comment by MellongLau** [comment]
解压`ipa`文件后`Payload` -> `app文件夹`下的`Info.plist`中`Bundle version`就是。

**Comment by jeffy7** [comment]
mkdir ~/Desktop/AM_Builds;xcrun -sdk iphoneos PackageApplication -v \"%@\" -o %@;open -R %@

我的意思是可以直接获取然后拼接在路径中么。例如：XXXX-20160701-104302.ipa,我现在想加一个build号，不是version。

**Comment by MellongLau** [comment]
`BUILD_NO=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" "${INFOPLIST_PATH}")`
`${INFOPLIST_PATH}`是Info.plist的文件路径。
