### ISSUE TITLE
请问一下,这个会生成dSYM文件吗？

### ISSUE THREAD

**Issue by songhuaixu** [MellongLau/AMAppExportToIPA-Xcode-Plugin#12]
我试了几次 没发现dSYM文件在哪。还有是选择的证书是什么打出来的ipa就是 什么类型的包吗？

**Comment by MellongLau** [comment]
好像是选Release build才有，Debug应该没有，具体你试试看。

**Comment by MellongLau** [comment]
`还有是选择的证书是什么打出来的ipa就是 什么类型的包吗？`
是的。

**Comment by songhuaixu** [comment]
你好，刚才我测试了一下，发现设置成Build Configuration设置成Release后，.app文件就不存在了。所以，这个方法好像行不通！

**Comment by MellongLau** [comment]
设置成Release后你要run一下

**Comment by songhuaixu** [comment]
确实是，我以前一直在Organizer 里面找，现在发现之前我想错了。谢谢。

**Comment by MellongLau** [comment]
不客气
