### ISSUE TITLE
XCode 8.3 不能用了

### ISSUE THREAD

**Issue by shixiaoda** [MellongLau/AMAppExportToIPA-Xcode-Plugin#14]
RT

**Comment by emsihyo** [comment]
+1

**Comment by MellongLau** [comment]
This is because Xcode 8.3 have removed `PackageApplication`, you can copy this component from the earlier Xcode, the following link is the detail of this temporary fix: 
www.jianshu.com/p/88bb51cba34d
I hope this will help.
