### ISSUE TITLE
Conflict with Stencil Plugin

### ISSUE THREAD

**Issue by oit63** [MellongLau/AMAppExportToIPA-Xcode-Plugin#2]
大腿，两个插件不兼容啊，我经常用Stencil 套模板，AMAppExportToIPA 和它不能共存呢，不然一打开Xcode 就崩溃了。
我怀疑是在处理右键菜单的那部分有冲突，因为两个插件都会修改右键菜单。

**Comment by MellongLau** [comment]
Thanks your feedback, this issue is fixed in: b28fb84

**Comment by tztTztTzt** [comment]
你好请问打包成功了 但是安装失败了 问题出在证书吗 但是 用xcode 自带的打包 证书又可以

**Comment by MellongLau** [comment]
@wryAndGithub 应该不是证书问题，你要看看 Build Setting的 Build Active Architecture Only是不是设置为NO
