### ISSUE TITLE
Context menu for issue navigator doesn't appear

### ISSUE THREAD

**Issue by dwicke01** [MellongLau/AMAppExportToIPA-Xcode-Plugin#3]
Right clicking an item on the issue navigator does not display a context menu. I did some digging because somebody raised an issue on a plugin I help maintain (HTYCopyIssue) and found that this is due to the menu created having zero items. I continued to not see a context menu after uninstalling HTYCopyIssue, and resumed seeing it after uninstalling AMAppExportToIPA.

**Comment by MellongLau** [comment]
Thanks your feedback, this issue is fixed in: b28fb846e6c3b8afa9aa5fc063790ea3e0fea971

**Comment by mythodeia** [comment]
excellent...thanks a lot. it works now

**Comment by MellongLau** [comment]
@mythodeia many thanks.
