### ISSUE TITLE
crash when opening context menu

### ISSUE THREAD

**Issue by mythodeia** [MellongLau/AMAppExportToIPA-Xcode-Plugin#4]
Hello
when i use your plugin with CopyIssue-Xcode-Plugin it causes a crash. I talked with the author of that plugin [here](https://github.com/hanton/CopyIssue-Xcode-Plugin/issues/26) and he was kind enough to help track the issue to your plugin. It seems yours is preventing the the context menu to appear which causes a crash. 
Can you take a look and make a fix so everyone can enjoy both these great plugins?
thanks

**Comment by MellongLau** [comment]
This issue may relate https://github.com/MellongLau/AMAppExportToIPA-Xcode-Plugin/issues/3, please try the latest version.

**Comment by mythodeia** [comment]
yeap...thanks :) i did not see that! closing this so you do not have duplicates

**Comment by MellongLau** [comment]
Thanks, please kindly help to test the v1.1 for this issue, I will close #3 if it can not be reproduced.
