### ISSUE TITLE
使用AMAppExprotToIPA 打包的ipa大小问题

### ISSUE THREAD

**Issue by tigerzhang08** [MellongLau/AMAppExportToIPA-Xcode-Plugin#5]
使用AMAppExprotToIPA 打包的ipa的size和Archive打包成的app在转化为ipa的size不同，差了将近8M。
不知道是不是编译或者打包选项不一致导致的，作者能说明下吗？

**Comment by MellongLau** [comment]
请参看： http://stackoverflow.com/questions/7323528/different-binaries-with-archive-and-build-for-archiving-in-xcode4
